[package]
name = "ultimate-tic-tac-toe"
version = "0.1.0"
edition = "2021"

[dependencies]
cached = "0.56.0"
clap = { version = "4.5.47", features = ["derive"] }
cmaes = { version = "0.2.2", default-features = false }
crossterm = "0.29.0"
rand = "0.8"
rayon = "1.11.0"
