[package]
name = "WeightedUTTT"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
cmaes = { version = "0.2.2", default-features = false }
crossterm = "0.29.0"
egobox-ego = "0.32.0"
genevo = "0.7.1"
